name: ronderos
description: Por una zona segura.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  cached_network_image: ^3.2.1
  google_fonts:
  image_picker: ^0.8.5+3
  google_nav_bar: ^5.0.6
  flutter_local_notifications: ^9.6.1

  #Firebase
  firebase_core:
  firebase_auth: 
  cloud_firestore:
  provider: ^6.0.3
  firebase_storage: ^10.2.17
  firebase_messaging: ^10.0.9
  fluttertoast: ^8.0.9
  #Cambiar splashart del app
  flutter_native_splash: ^2.2.3+1


# Para cambiar el icono de nuevo:
  # flutter clean && flutter pub get 
  # flutter pub run 
  # flutter_native_splash:create

flutter_native_splash:
  image: assets/Logo_ronderos.png
  color: "#ffffff"
  #background_image: ""

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #Agregar Icono
  flutter_launcher_icons: ^0.9.3

#Agregar el path del icono
flutter_icons:
  image_path: "assets/Icono_ronderos.png"
  android: true
  IOS: true
  
# Para cambiar el icono de nuevo:
  # flutter clean 
  # flutter pub get 
  # flutter pub run flutter_launcher_icons:main
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

#Cambiar nombre y ID del app con dependencie
  # flutter pub global activate rename
  # flutter pub global run rename --appname "_______" 
  # flutter pub global run rename --bundleId "com.NOMBRE_APELLIDO.NOMBRE_APP"
